# Generated by Django 6.0.4 on 2026-04-09 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_link', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='note_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notes')),
            ],
        ),
        migrations.CreateModel(
            name='accesseble_notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notes')),
            ],
        ),
        migrations.CreateModel(
            name='prof_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notes')),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('delete', 'Delete'), ('update', 'Update')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
    ]
