# Generated by Django 6.0.4 on 2026-04-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_groups_notes_note_group_accesseble_notes_prof_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
