# Generated by Django 6.0.4 on 2026-04-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_requests_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='prof_id',
            new_name='profile',
        ),
    ]
