# Generated by Django 6.0.4 on 2026-04-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_prof_id_notes_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='file_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
