# Generated by Django 6.0.4 on 2026-04-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notes_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
