# Generated by Django 6.0.4 on 2026-04-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_link',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
