# Generated by Django 6.0.4 on 2026-04-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notes_file_link_alter_notes_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesseble_notes',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='accesseble_notes',
            old_name='prof_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='note_group',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='note_group',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='prof_group',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='prof_group',
            old_name='prof_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='prof_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='prof_id',
            new_name='profile',
        ),
    ]
