# Generated by Django 6.0.4 on 2026-04-15 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_note_id_accesseble_notes_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_an',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accesseble_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accesseble_notes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
            ],
        ),
    ]
