# Generated by Django 6.0.4 on 2026-04-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_group_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='file_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
