services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: multicontroller
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 0000
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:  
    build: ./backend
    ports:
      - "8010:8010"
    depends_on:
      - db
    environment:
      - DB_NAME=multicontroller
      - DB_USER=root
      - DB_PASSWORD=0000
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./backend:/app  # ← синхронизация кода

  web:
    build: ./multicontroller_frontend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://api:8010
    depends_on:
      - api
    volumes:
      - ./multicontroller_frontend:/app  # ← синхронизация кода

volumes:
  postgres_data: